[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ast = true
build_info = true
extra_output = ["storageLayout"]
auto_detect_solc = true  # Enable auto-detection of solc versions, this allows the use of files with different solc versions

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
